/**
 * WorkflowVersion schema — persisted version history for an automation.
 *
 * Every successful generation or manual save creates a new version row.
 * This enables:
 *   - Rollback to any prior version
 *   - Audit trail (who/when/what generated)
 *   - A/B testing prompt strategies
 *   - Diff view between versions
 *
 * The version row is the source of truth for the IR. The `automations`
 * table holds a denormalized "current" pointer for fast reads, but the
 * version table is canonical.
 */

import { z } from "zod";
import { workflowIRSchema } from "./workflow";

/**
 * How was this version produced?
 *   openai        — generated by OpenAI provider
 *   claude        — generated by Claude provider (future)
 *   gemini        — generated by Gemini provider (future)
 *   fallback      — generated by deterministic fallback (no API key)
 *   manual        — user edited via UI (future)
 *   import        — imported from external source (future)
 */
export const VERSION_SOURCES = [
  "openai",
  "claude",
  "gemini",
  "fallback",
  "manual",
  "import",
] as const;

export const versionSourceSchema = z.enum(VERSION_SOURCES);
export type VersionSource = z.infer<typeof versionSourceSchema>;

export const workflowVersionSchema = z
  .object({
    id: z.string().uuid(),

    /** Owning automation. */
    automationId: z.string().uuid(),

    /** Owning user (denormalized for RLS + fast lookup). */
    userId: z.string().uuid(),

    /** Monotonic per-automation version counter, starts at 1. */
    versionNumber: z.number().int().positive(),

    /** Frozen IR snapshot. Immutable once written. */
    workflow: workflowIRSchema,

    /** Original prompt that produced this version. */
    prompt: z.string().trim().min(1).max(2000).nullable(),

    source: versionSourceSchema,

    /** Cost in credits at generation time (auditing). */
    cost: z.number().int().nonnegative().default(0),

    /**
     * Whether this version is the currently active one for the
     * automation. Exactly one version per automation has activated=true.
     */
    activated: z.boolean().default(true),

    /** Free-form provider metadata (model name, reasoning effort, ...). */
    metadata: z
      .record(z.string(), z.unknown())
      .default({}),

    createdAt: z.string(),
  })
  .strict();

export type WorkflowVersion = z.infer<typeof workflowVersionSchema>;

/**
 * Input shape for creating a new version (omits server-managed fields).
 */
export const createWorkflowVersionInputSchema = workflowVersionSchema
  .pick({
    workflow: true,
    prompt: true,
    source: true,
    cost: true,
    metadata: true,
  })
  .extend({
    automationId: z.string().uuid(),
    userId: z.string().uuid(),
  });

export type CreateWorkflowVersionInput = z.infer<
  typeof createWorkflowVersionInputSchema
>;
